# Generated by Django 4.0.4 on 2022-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_url_project_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
